version: "3"
services: 
    web:
        build: .
        volumes: 
            - .:/home/node/src
            - /home/node/node_modules
        environment: 
            MONGO_CONNECTION_STRING: mongodb://db:27017
        links: 
            - db
        ports: 
            - "3000:3000"
    db:    
        image: "mongo:latest"